name: run sanity check
run-name: ${{ github.actor }} did push so lets sanity check
on: [push]
jobs:
  sanity-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: ls $GITHUB_WORKSPACE
      - run: cd $GITHUB_WORKSPACE
      - run: ansible-galaxy collection build $GITHUB_WORKSPACE
      - run: ansible-galaxy collection install ./ibm-zvm_ansible*.tar.gz
      - run: ansible-test sanity --requirements --docker --python 3.11
